name: K6 Performance Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  load-test:
    name: Run Load Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create results directory
      run: mkdir -p results
      
    - name: Run K6 tests
      uses: grafana/k6-action@v0.3.0
      with:
        filename: src/tests/load/load_test.js
        output: |
          results/load_test.json
          results/report.html
      
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: k6-results
        path: results/
        if-no-files-found: warn
