name: K6 Performance Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  load-test:
    name: Run Load Tests
    runs-on: ubuntu-latest
    container:
      image: grafana/k6:latest
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create results directory
      run: mkdir -p results
    
    - name: Run Load Test
      run: |
        echo "Starting K6 performance tests..."
        k6 run src/tests/load/load_test.js \
          --out json=results/load_test.json \
          --out html=results/report.html
        echo "Test completed"
        
    - name: Upload Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: k6-test-results
        path: results/
